// src/services/autoExportService.ts
//
// vocabulary.txt now contains BOTH tables in one file:
//
//   ════════════════════════════════════════════════════════════
//   [DICTIONARY WORDS]   ← from saved_words table
//   ════════════════════════════════════════════════════════════
//   Word: Robust
//   Meaning: Strong and successful
//   Example: The economy showed robust growth.
//   POS: adjective
//   Source: chapter1.pdf
//
//   ---
//
//   ════════════════════════════════════════════════════════════
//   [CUSTOM VOCABULARY]  ← from custom_vocab table
//   ════════════════════════════════════════════════════════════
//   Word: Revenue
//   Meaning: Total income generated by a business
//   Source: report.pdf
//
//   ---
//
// sentences.txt is unchanged (only custom_sentences table).

import * as FileSystem from 'expo-file-system/legacy';
import {
  getAllWords,
  getAllCustomVocab,
  getAllCustomSentences,
  SavedWord,
  CustomVocabEntry,
  CustomSentenceEntry,
} from '../database/database';

// ─── Paths ───────────────────────────────────────────────────────────────────

const FOLDER = `${FileSystem.documentDirectory}VocabPDF/`;

export const VOCAB_TXT_PATH     = `${FOLDER}vocabulary.txt`;
export const SENTENCES_TXT_PATH = `${FOLDER}sentences.txt`;

// ─── Folder bootstrap ────────────────────────────────────────────────────────

const ensureFolder = async (): Promise<void> => {
  try {
    const info = await FileSystem.getInfoAsync(FOLDER);
    if (!info.exists) {
      await FileSystem.makeDirectoryAsync(FOLDER, { intermediates: true });
    }
  } catch (err) {
    console.error('[AutoExport] ensureFolder:', err);
  }
};

// ─── Formatters ──────────────────────────────────────────────────────────────

/**
 * Build vocabulary.txt content from BOTH saved_words + custom_vocab.
 * Both tables are written into the single file with clear section headers.
 */
const buildVocabContent = (
  savedWords:   SavedWord[],
  customVocab:  CustomVocabEntry[],
): string => {
  const totalEntries = savedWords.length + customVocab.length;
  const SEP = '─'.repeat(60);
  const THICK = '═'.repeat(60);

  let out = '# PDF Vocabulary Reader — All Vocabulary\n';
  out    += `# Total entries: ${totalEntries}`;
  out    += ` (${savedWords.length} dictionary + ${customVocab.length} custom)\n`;
  out    += `# Last updated: ${new Date().toLocaleString()}\n`;
  out    += THICK + '\n\n';

  // ── Section 1: Dictionary / Saved Words ──────────────────────────────────
  out += `[DICTIONARY WORDS] — ${savedWords.length} entries\n`;
  out += THICK + '\n\n';

  if (savedWords.length === 0) {
    out += '# No dictionary words saved yet.\n\n';
  } else {
    for (const w of savedWords) {
      out += `Word: ${w.word}\n`;
      out += `Meaning: ${w.meaning}\n`;
      if (w.example)      out += `Example: ${w.example}\n`;
      if (w.partOfSpeech) out += `POS: ${w.partOfSpeech}\n`;
      if (w.pdfSource)    out += `Source: ${w.pdfSource}\n`;
      out += '\n---\n\n';
    }
  }

  // ── Section 2: Custom Vocabulary ─────────────────────────────────────────
  out += `[CUSTOM VOCABULARY] — ${customVocab.length} entries\n`;
  out += THICK + '\n\n';

  if (customVocab.length === 0) {
    out += '# No custom vocabulary entries yet.\n\n';
  } else {
    for (const e of customVocab) {
      out += `Word: ${e.word}\n`;
      out += `Meaning: ${e.meaning}\n`;
      if (e.pdfSource) out += `Source: ${e.pdfSource}\n`;
      out += '\n---\n\n';
    }
  }

  return out;
};

/** Build sentences.txt from custom_sentences table. */
const buildSentencesContent = (entries: CustomSentenceEntry[]): string => {
  const THICK = '═'.repeat(60);

  let out = '# PDF Vocabulary Reader — Custom Sentences\n';
  out    += `# Total entries: ${entries.length}\n`;
  out    += `# Last updated: ${new Date().toLocaleString()}\n`;
  out    += THICK + '\n\n';

  if (entries.length === 0) {
    out += '# No sentence entries yet.\n';
    return out;
  }

  for (const e of entries) {
    out += `Sentence:\n${e.sentence}\n\n`;
    out += `Meaning:\n${e.meaning}\n`;
    if (e.pdfSource) out += `Source: ${e.pdfSource}\n`;
    out += '\n---\n\n';
  }

  return out;
};

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Rebuild vocabulary.txt from BOTH saved_words AND custom_vocab tables.
 * Call this after any change to either table:
 *   - saveWord / deleteWord (saved_words)
 *   - saveCustomVocab / deleteCustomVocab (custom_vocab)
 */
export const syncVocabTxt = async (): Promise<void> => {
  try {
    await ensureFolder();
    const [savedWords, customVocab] = await Promise.all([
      getAllWords(),
      getAllCustomVocab(),
    ]);
    const content = buildVocabContent(savedWords, customVocab);
    await FileSystem.writeAsStringAsync(VOCAB_TXT_PATH, content, {
      encoding: FileSystem.EncodingType.UTF8,
    });
  } catch (err) {
    console.error('[AutoExport] syncVocabTxt:', err);
  }
};

/**
 * Rebuild sentences.txt from custom_sentences table.
 * Call after any add / edit / delete of a sentence entry.
 */
export const syncSentencesTxt = async (): Promise<void> => {
  try {
    await ensureFolder();
    const entries = await getAllCustomSentences();
    const content = buildSentencesContent(entries);
    await FileSystem.writeAsStringAsync(SENTENCES_TXT_PATH, content, {
      encoding: FileSystem.EncodingType.UTF8,
    });
  } catch (err) {
    console.error('[AutoExport] syncSentencesTxt:', err);
  }
};

/** Sync both files — called on app startup. */
export const syncAllTxt = async (): Promise<void> => {
  await Promise.all([syncVocabTxt(), syncSentencesTxt()]);
};

export const getExportPaths = () => ({
  vocab:     VOCAB_TXT_PATH,
  sentences: SENTENCES_TXT_PATH,
  folder:    FOLDER,
});
