// src/services/exportService.ts
// Handles exporting vocabulary as TXT files
// Generates formatted vocabulary notes for sharing/saving

import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from 'expo-sharing';
import { SavedWord } from '../database/database';
// Generate a formatted TXT vocabulary notes file
export const exportAsTxt = async (words: SavedWord[]): Promise<boolean> => {
  try {
    const date = new Date().toLocaleDateString('en-IN', {
      day: '2-digit',
      month: 'long',
      year: 'numeric',
    });

    let content = `PDF VOCABULARY READER — VOCABULARY NOTES\n`;
    content += `Generated: ${date}\n`;
    content += `Total Words: ${words.length}\n`;
    content += `${'='.repeat(60)}\n\n`;

    words.forEach((item, index) => {
      const synonyms = (() => {
        try {
          const parsed = JSON.parse(item.synonyms);
          return Array.isArray(parsed) ? parsed : [];
        } catch {
          return [];
        }
      })();

      content += `${index + 1}. ${item.word.toUpperCase()}\n`;
      if (item.partOfSpeech) content += `   [${item.partOfSpeech}]\n`;
      content += `   Meaning: ${item.meaning}\n`;
      if (synonyms.length > 0) {
        content += `   Synonyms: ${synonyms.join(', ')}\n`;
      }
      if (item.example) {
        content += `   Example: "${item.example}"\n`;
      }
      content += `   Saved: ${new Date(item.savedDate).toLocaleDateString()}\n`;
      content += `${'-'.repeat(50)}\n\n`;
    });

    content += `\n[Generated by PDF Vocabulary Reader]\n`;

    const fileName = `vocabulary_notes_${Date.now()}.txt`;
    const fileUri = `${FileSystem.documentDirectory}${fileName}`;
    
    await FileSystem.writeAsStringAsync(fileUri, content, {
      encoding: FileSystem.EncodingType.UTF8,
    });

    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(fileUri, {
        mimeType: 'text/plain',
        dialogTitle: 'Share Vocabulary Notes',
      });
    }

    return true;
  } catch (error) {
    console.error('Export error:', error);
    return false;
  }
};

// Generate a simple HTML-based vocabulary report (shareable as HTML)
export const exportAsHtml = async (words: SavedWord[]): Promise<boolean> => {
  try {
    const date = new Date().toLocaleDateString('en-IN', {
      day: '2-digit',
      month: 'long',
      year: 'numeric',
    });

    let rows = '';
    words.forEach((item, index) => {
      const synonyms = (() => {
        try {
          const parsed = JSON.parse(item.synonyms);
          return Array.isArray(parsed) ? parsed.join(', ') : '';
        } catch {
          return '';
        }
      })();

      rows += `
        <tr>
          <td class="num">${index + 1}</td>
          <td class="word">${item.word}</td>
          <td class="pos">${item.partOfSpeech || '-'}</td>
          <td>${item.meaning}</td>
          <td class="syn">${synonyms || '-'}</td>
          <td class="example">${item.example ? `"${item.example}"` : '-'}</td>
        </tr>
      `;
    });

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Vocabulary Notes</title>
  <style>
    body { font-family: Georgia, serif; margin: 40px; background: #fafafa; color: #222; }
    h1 { color: #6C63FF; border-bottom: 3px solid #6C63FF; padding-bottom: 10px; }
    .meta { color: #666; margin-bottom: 30px; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
    th { background: #6C63FF; color: white; padding: 12px 16px; text-align: left; }
    td { padding: 10px 16px; border-bottom: 1px solid #eee; vertical-align: top; }
    tr:last-child td { border-bottom: none; }
    tr:nth-child(even) { background: #f9f9ff; }
    .word { font-weight: bold; color: #6C63FF; font-size: 16px; }
    .pos { color: #888; font-style: italic; font-size: 13px; }
    .syn { color: #43D9AD; font-size: 13px; }
    .example { font-style: italic; color: #555; font-size: 13px; }
    .num { color: #aaa; font-size: 13px; }
    footer { text-align: center; margin-top: 40px; color: #aaa; font-size: 13px; }
  </style>
</head>
<body>
  <h1>📚 Vocabulary Notes</h1>
  <div class="meta">Generated: ${date} &nbsp;|&nbsp; Total Words: ${words.length}</div>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Word</th>
        <th>Type</th>
        <th>Meaning</th>
        <th>Synonyms</th>
        <th>Example</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <footer>Generated by PDF Vocabulary Reader</footer>
</body>
</html>`;

    const fileName = `vocabulary_notes_${Date.now()}.html`;
    const fileUri = `${FileSystem.documentDirectory}${fileName}`;

    await FileSystem.writeAsStringAsync(fileUri, html, {
      encoding: FileSystem.EncodingType.UTF8,
    });

    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(fileUri, {
        mimeType: 'text/html',
        dialogTitle: 'Share Vocabulary Notes',
      });
    }

    return true;
  } catch (error) {
    console.error('HTML export error:', error);
    return false;
  }
};
